services:
  abcall-pqrs-db:
    image: postgres:15.4
    environment:
      POSTGRES_DB: pqrsdb
      POSTGRES_USER: pqrsuser
      POSTGRES_PASSWORD: pqrspassword
    ports:
      - "5432:5432"
    volumes:
      - pqrs-db-data:/var/lib/postgresql/data
    networks:
      - chalice-network

  abcall-users-db:
    image: postgres:15.4
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: usersuser
      POSTGRES_PASSWORD: userpassword
    ports:
      - "5435:5432"
    volumes:
      - users-db-data:/var/lib/postgresql/data
    networks:
      - chalice-network

  abcall-clients-db:
    image: postgres:15.4
    environment:
      POSTGRES_DB: clientsdb
      POSTGRES_USER: clientuser
      POSTGRES_PASSWORD: clientpassword
    ports:
      - "5436:5432"
    volumes:
      - clients-db-data:/var/lib/postgresql/data
    networks:
      - chalice-network

#  abcall-pqrs-events-db:
#    image: postgres:15.4
#    environment:
#      POSTGRES_DB: pqrsdb
#      POSTGRES_USER: pqrsuser
#      POSTGRES_PASSWORD: pqrspassword
#    ports:
#      - "5433:5432"
#    volumes:
#      - pqrs-events-db-data:/var/lib/postgresql/data
#    networks:
#      - chalice-network

  abcall-pqrs-microservice:
    build:
      context: ./abcall-pqrs-microservice
    command: chalice local
    ports:
      - "3000:3000"
    volumes:
      - ./abcall-pqrs-microservice:/app
      - ~/.aws:/root/.aws # Montar las credenciales de AWS en el contenedor
    environment:
      - DATABASE_URL=postgresql://pqrsuser:pqrspassword@abcall-pqrs-db:5432/pqrsdb
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - chalice-network
    depends_on:
      - abcall-pqrs-db

  abcall-pqrs-events-microservice:
    build:
      context: ./abcall-pqrs-events-microservice
    command: chalice local
    ports:
      - "3001:3000"
    volumes:
      - ./abcall-pqrs-events-microservice:/app
      - ~/.aws:/root/.aws # Montar las credenciales de AWS en el contenedor
    environment:
      - DATABASE_URL=postgresql://pqrsuser:pqrspassword@abcall-pqrs-db:5432/pqrsdb
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - chalice-network
    depends_on:
      - abcall-pqrs-db

  abcall-users-microservice:
    build:
      context: ./abcall-users-microservice
    command: chalice local
    ports:
      - "3002:3000"
    volumes:
      - ./abcall-users-microservice:/app
      - ~/.aws:/root/.aws # Montar las credenciales de AWS en el contenedor
    environment:
      - DATABASE_URL=postgresql://usersuser:userpassword@abcall-users-db:5435/usersdb
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - chalice-network
    depends_on:
      - abcall-users-db

  abcall-clients-microservice:
    build:
      context: ./abcall-clients-microservice
    command: chalice local
    ports:
      - "3003:3000"
    volumes:
      - ./abcall-clients-microservice:/app
      - ~/.aws:/root/.aws # Montar las credenciales de AWS en el contenedor
    environment:
      - DATABASE_URL=postgresql://clientsuser:clientpassword@abcall-clients-db:5436/clientsdb
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - chalice-network
    depends_on:
      - abcall-clients-db

volumes:
  pqrs-db-data:
  pqrs-events-db-data:
  users-db-data:
  clients-db-data:

networks:
  chalice-network:
