version: 0.2

phases:
  install:
    commands:
      - pip install chalice
      - pip install -r requirements.txt
      - pip install pytest
  pre_build:
    commands:
      - echo "Preparing build..."
  build:
    commands:
      - echo "Running Chalice Tests..."
      - pytest tests/
  post_build:
    commands:
      - echo "Build complete."
artifacts:
  base-directory: build
  files:
    - '**/*'
reports:
  test-report:
    files:
      - "**/pytest*.xml"
