version: 0.2

phases:
  install:
    commands:
      - pip install chalice
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Deploying Chalice App..."
      - chalice deploy --no-autogen-policy