AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ChaliceAbcallPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: ChaliceAbcallPipeline
      RoleArn: arn:aws:iam::<account-id>:role/service-role/AWSCodePipelineServiceRole
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                RepositoryName: abcall-pqrs-events-microservice
                BranchName: main
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: abcall-pqrs-events-build
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: abcall-pqrs-events-deploy
